let _dayArray = [
    {weather : { icon: "icons/storm.png", code : 200,  sound: "sound/thunderstorm.mp3"}},
    {weather : { icon: "icons/storm.png", code : 201,  sound: "sound/thunderstorm.mp3"}},
    {weather : { icon: "icons/storm.png", code : 202,  sound: "sound/thunderstorm.mp3"}},
    {weather : { icon: "icons/storm.png", code : 210,  sound: "sound/thunderstorm.mp3"}},
    {weather : { icon: "icons/storm.png", code : 211,  sound: "sound/thunderstorm.mp3"}},
    {weather : { icon: "icons/storm.png", code : 212,  sound: "sound/thunderstorm.mp3"}},
    {weather : { icon: "icons/storm.png", code : 221,  sound: "sound/thunderstorm.mp3"}},
    {weather : { icon: "icons/storm.png", code : 230,  sound: "sound/thunderstorm.mp3"}},
    {weather : { icon: "icons/storm.png", code : 231,  sound: "sound/thunderstorm.mp3"}},
    {weather : { icon: "icons/storm.png", code : 232,  sound: "sound/thunderstorm.mp3"}},

    {weather : { icon: "icons/drizzle-sun.png", code : 300,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 301,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 302,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 310,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 311,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 312,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 313,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 314,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 321,  sound: "sound/rain.mp3"}},

    {weather : { icon: "icons/drizzle-sun.png", code : 500,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 501,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 502,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 503,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 504,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 511,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 520,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 521,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 522,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 531,  sound: "sound/rain.mp3"}},

    {weather : { icon: "icons/snow-sun.png", code : 600,  sound: "sound/snow.mp3"}},
    {weather : { icon: "icons/snow.png", code : 601,  sound: "sound/snow.mp3"}},
    {weather : { icon: "icons/snow.png", code : 602,  sound: "sound/snow.mp3"}},
    {weather : { icon: "icons/snow-rain.png", code : 611,  sound: "sound/snow.mp3"}},
    {weather : { icon: "icons/snow-rain.png", code : 612,  sound: "sound/snow.mp3"}},
    {weather : { icon: "icons/snow-rain.png", code : 613,  sound: "sound/snow.mp3"}},
    {weather : { icon: "icons/snow-rain.png", code : 615,  sound: "sound/snow.mp3"}},
    {weather : { icon: "icons/snow-rain.png", code : 616,  sound: "sound/snow.mp3"}},
    {weather : { icon: "icons/snow-rain.png", code : 620,  sound: "sound/snow.mp3"}},
    {weather : { icon: "icons/snow-rain.png", code : 621,  sound: "sound/snow.mp3"}},
    {weather : { icon: "icons/snow-rain.png", code : 622,  sound: "sound/snow.mp3"}},

    {weather : { icon: "icons/fog.png", code : 700,  sound: "sound/day.mp3"}},
    {weather : { icon: "icons/fog.png", code : 701,  sound: "sound/day.mp3"}},
    {weather : { icon: "icons/fog.png", code : 721,  sound: "sound/day.mp3"}},
    {weather : { icon: "icons/dust.png", code : 731,  sound: "sound/wind.mp3"}},
    {weather : { icon: "icons/fog.png", code : 741,  sound: "sound/day.mp3"}},
    {weather : { icon: "icons/dust.png", code : 751,  sound: "sound/wind.mp3"}},
    {weather : { icon: "icons/dust.png", code : 761,  sound: "sound/wind.mp3"}},
    {weather : { icon: "icons/fog.png", code : 762,  sound: "sound/wind.mp3"}},
    {weather : { icon: "icons/fog.png", code : 771,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/tornado.png", code : 781,  sound: "sound/wind.mp3"}},

    {weather : { icon: "icons/sun.png", code : 800,  sound: "sound/day.mp3"}},
    {weather : { icon: "icons/partly-cloudy.png", code : 801, sound: "sound/day.mp3"}},
    {weather : { icon: "icons/cloud.png", code : 802, sound: "sound/day.mp3"}},
    {weather : { icon: "icons/cloud.png", code : 803, sound: "sound/day.mp3"}},
    {weather : { icon: "icons/cloud-dark.png", code : 804, sound: "sound/day.mp3"}},
]

let _nightArray = [

    {weather : { icon: "icons/storm.png", code : 200,  sound: "sound/thunderstorm.mp3"}},
    {weather : { icon: "icons/storm.png", code : 201,  sound: "sound/thunderstorm.mp3"}},
    {weather : { icon: "icons/storm.png", code : 202,  sound: "sound/thunderstorm.mp3"}},
    {weather : { icon: "icons/storm.png", code : 210,  sound: "sound/thunderstorm.mp3"}},
    {weather : { icon: "icons/storm.png", code : 211,  sound: "sound/thunderstorm.mp3"}},
    {weather : { icon: "icons/storm.png", code : 212,  sound: "sound/thunderstorm.mp3"}},
    {weather : { icon: "icons/storm.png", code : 221,  sound: "sound/thunderstorm.mp3"}},
    {weather : { icon: "icons/storm.png", code : 230,  sound: "sound/thunderstorm.mp3"}},
    {weather : { icon: "icons/storm.png", code : 231,  sound: "sound/thunderstorm.mp3"}},
    {weather : { icon: "icons/storm.png", code : 232,  sound: "sound/thunderstorm.mp3"}},

    {weather : { icon: "icons/drizzle-moon.png", code : 300,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 301,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 302,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 310,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 311,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 312,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 313,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 314,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 321,  sound: "sound/rain.mp3"}},

    {weather : { icon: "icons/drizzle-moon.png", code : 500,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 501,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 502,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 503,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 504,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 511,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 520,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 521,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 522,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/rain.png", code : 531,  sound: "sound/rain.mp3"}},

    {weather : { icon: "icons/snow-moon.png", code : 600,  sound: "sound/snow.mp3"}},
    {weather : { icon: "icons/snow.png", code : 601,  sound: "sound/snow.mp3"}},
    {weather : { icon: "icons/snow.png", code : 602,  sound: "sound/snow.mp3"}},
    {weather : { icon: "icons/snow.png", code : 611,  sound: "sound/snow.mp3"}},
    {weather : { icon: "icons/snow.png", code : 612,  sound: "sound/snow.mp3"}},
    {weather : { icon: "icons/snow.png", code : 613,  sound: "sound/snow.mp3"}},
    {weather : { icon: "icons/snow.png", code : 615,  sound: "sound/snow.mp3"}},
    {weather : { icon: "icons/snow.png", code : 616,  sound: "sound/snow.mp3"}},
    {weather : { icon: "icons/snow.png", code : 620,  sound: "sound/snow.mp3"}},
    {weather : { icon: "icons/snow.png", code : 621,  sound: "sound/snow.mp3"}},
    {weather : { icon: "icons/snow.png", code : 622,  sound: "sound/snow.mp3"}},

    {weather : { icon: "icons/fog.png", code : 700,  sound: "sound/day.mp3"}},
    {weather : { icon: "icons/fog.png", code : 701,  sound: "sound/day.mp3"}},
    {weather : { icon: "icons/fog.png", code : 721,  sound: "sound/day.mp3"}},
    {weather : { icon: "icons/dust.png", code : 731,  sound: "sound/wind.mp3"}},
    {weather : { icon: "icons/fog.png", code : 741,  sound: "sound/day.mp3"}},
    {weather : { icon: "icons/dust.png", code : 751,  sound: "sound/wind.mp3"}},
    {weather : { icon: "icons/dust.png", code : 761,  sound: "sound/wind.mp3"}},
    {weather : { icon: "icons/fog.png", code : 762,  sound: "sound/wind.mp3"}},
    {weather : { icon: "icons/fog.png", code : 771,  sound: "sound/rain.mp3"}},
    {weather : { icon: "icons/tornado.png", code : 781,  sound: "sound/wind.mp3"}},

    {weather : { icon: "icons/moon.png", code : 800, sound: "sound/night.mp3"}},
    {weather : { icon: "icons/partly-cloudy-moon.png", code : 801,  sound: "sound/night.mp3"}},
    {weather : { icon: "icons/cloud.png", code : 802,  sound: "sound/night.mp3"}},
    {weather : { icon: "icons/cloud.png", code : 802,  sound: "sound/night.mp3"}},
    {weather : { icon: "icons/cloud.png", code : 803,  sound: "sound/night.mp3"}},
    {weather : { icon: "icons/cloud-dark.png", code : 804,  sound: "sound/night.mp3"}},
]